#!/bin/bash

# Usage
if [ -z "$1" -o -z "$2" ]; then
	echo "Usage: `basename $0` [options] [path/to/wallpaper] [theme_name]"
	echo "	 	options:"
	echo "			[none]  generate all colors"
	echo "			-w    only generate waybar colors"
	echo
	exit 0
fi

only_waybar=0
if [ "$1" = '-w' ]; then 
	only_waybar=1
	shift
fi

# Check if wallpaper exists
if [ ! -f "$1" ]; then
	echo "`basename $0`: $1 doesn\'t exist"
	echo
fi

WAL_CACHE="$HOME/.cache/wal"
COLORS_CONF="$HOME/.config/hypr/themes/$2/"


# Waybar

WAYBAR_PATH="$HOME/.config/waybar"
[ ! -d "$WAYBAR_PATH" ] && exit 0
[ ! -d "$WAYBAR_PATH/themes/$2" ] && mkdir -p "$WAYBAR_PATH/themes/$2"

# Generate colors and load
wal -i "$1" -nstq
source "$WAL_CACHE/colors.sh"

cat > "$WAYBAR_PATH/themes/$2/waybar_colors.css" << EOF
@define-color color_bg_transp \
	$(echo ${color0:1} | \
	awk '{print "ibase=16;"toupper(substr($0,1,2))";" toupper(substr($0,3,2))";" toupper(substr($0,5,2))}' | bc | \
	xargs echo | awk '{print "rgba ("$1", " $2", " $3 ", 0.8)" }');

@define-color color_bg $color0;
@define-color color_primary $color1;
@define-color color_secondary $color2;
@define-color color_secondary_alt $color3;
@define-color color_info $color4;
@define-color color_highlight $color5;
@define-color color_text_muted $color6;
@define-color color_text $color7;
@define-color color_bg_alt $color8;
@define-color color1 $color9;
@define-color color2 $color10;
@define-color color3 $color11;
@define-color color4 $color12;
@define-color color5 $color13;
@define-color color6 $color14;
@define-color color7 $color15;
EOF
# if only waybar then exit
if [ "$only_waybar" -eq 1 ]; then
	exit 0
fi


# Check if the theme already exists
if [ -d $COLORS_CONF ]; then
	read -p "`basename $0`: theme $2 already exists, do you want to overwrite colors? [Y/n] " -n 1 -r
	echo
	if [[ ! $REPLY =~ ^[Yy]$ ]]; then
		exit 0
	fi
else
	mkdir $COLORS_CONF
fi

# create and load the autogenerated colors
# wal -i "$1" -nstq
# source "$WAL_CACHE/colors.sh"

# For loop to generate colors/colors_bright
for i in "colors" "colors_bright"; do
	# Create colors.conf
	cat > "$COLORS_CONF/$i.conf" << EOF
# Autogenerated by Pywal
\$color_bg = rgb(${color0#'#'})
\$color_primary = rgb(${color1#'#'})
\$color_secondary = rgb(${color2#'#'})
\$color_secondary_alt = rgb(${color3#'#'})
\$color_info = rgb(${color4#'#'})
\$color_highlight = rgb(${color5#'#'})
\$color_text_muted = rgb(${color6#'#'})
\$color_text = rgb(${color7#'#'})
\$color_bg_alt = rgb(${color8#'#'})
\$color1 = rgb(${color9#'#'})
\$color2 = rgb(${color10#'#'})
\$color3 = rgb(${color11#'#'})
\$color4 = rgb(${color12#'#'})
\$color5 = rgb(${color13#'#'})
\$color6 = rgb(${color14#'#'})
\$color7 = rgb(${color15#'#'})
EOF
wal -i "$1" -nstq --saturate 0.5
done

