#!/bin/bash

# Usage
if [ -z "$1" -o -z "$2" ]; then
	echo "Usage: `basename $0` [path/to/wallpaper] [them_name]"
	echo
	exit 0
fi

# Check if wallpaper exists
if [ ! -f "$1" ]; then
	echo "`basename $0`: $1 doesn\'t exist"
	echo
fi

WAL_CACHE="$HOME/.cache/wal"
COLORS_CONF="$HOME/.config/hypr/themes/$2/"

# Check if the theme already exists
if [ -d $COLORS_CONF ]; then
	read -p "`basename $0`: theme $2 already exists, do you want to overwrite colors? [Y/n] " -n 1 -r
	echo
	if [[ ! $REPLY =~ ^[Yy]$ ]]; then
		exit 0
	fi
else
	mkdir $COLORS_CONF
fi

# create and load the autogenerated colors
wal -i "$1" -nstq
source "$WAL_CACHE/colors.sh"

# Create colors.conf
cat > "$COLORS_CONF/colors.conf" << EOF
# Autogenerated by Pywal
\$color_bg = rgb(${color0#'#'})
\$color_primary = rgb(${color1#'#'})
\$color_secondary = rgb(${color2#'#'})
\$color_secondary_alt = rgb(${color3#'#'})
\$color_info = rgb(${color4#'#'})
\$color_highlight = rgb(${color5#'#'})
\$color_text_muted = rgb(${color6#'#'})
\$color_text = rgb(${color7#'#'})
\$color_bg_alt = rgb(${color8#'#'})
\$color1 = rgb(${color9#'#'})
\$color2 = rgb(${color10#'#'})
\$color3 = rgb(${color11#'#'})
\$color4 = rgb(${color12#'#'})
\$color5 = rgb(${color13#'#'})
\$color6 = rgb(${color14#'#'})
\$color7 = rgb(${color15#'#'})
EOF

# Same for saturated colors
wal -i "$1" -nstq --saturate 0.5

cat > "$COLORS_CONF/colors_bright.conf" << EOF
# Autogenerated by Pywal
\$color_bg = rgb(${color0#'#'})
\$color_primary = rgb(${color1#'#'})
\$color_secondary = rgb(${color2#'#'})
\$color_secondary_alt = rgb(${color3#'#'})
\$color_info = rgb(${color4#'#'})
\$color_highlight = rgb(${color5#'#'})
\$color_text_muted = rgb(${color6#'#'})
\$color_text = rgb(${color7#'#'})
\$color_bg_alt = rgb(${color8#'#'})
\$color1 = rgb(${color9#'#'})
\$color2 = rgb(${color10#'#'})
\$color3 = rgb(${color11#'#'})
\$color4 = rgb(${color12#'#'})
\$color5 = rgb(${color13#'#'})
\$color6 = rgb(${color14#'#'})
\$color7 = rgb(${color15#'#'})
EOF

